### ISSUE TITLE
Issue when using apscheduler execfile('test.py')

### ISSUE THREAD

**Issue by TomoyaJ** [TomoyaJ/Python2#1]
I was trying to use apscheduler to execute my python file named SetTimeAutoRun.py which was include one function for execfile('test.py').
in test.py file I called HTMLTestRunner to execute my all testsuite.

then I getting below error(if comments the code for apscheduler part and direct run the function execfile('test.py') then no any issues):

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\apscheduler\scheduler.py", line 512, in _run_job
    retval = job.func(*job.args, **job.kwargs)
  File "E:\Project\SetTimeAutoRun.py", line 11, in executetestcase
    execfile('/test.py')
  File "E:\Project/test.py", line 60, in <module>
    runner.run(testunit)
  File "C:\Python27\lib\HTMLTestRunner.py", line 642, in run
    self.generateReport(test, result)
  File "C:\Python27\lib\unittest\suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "C:\Python27\lib\unittest\suite.py", line 100, in run
    self._handleClassSetUp(test, result)
  File "C:\Python27\lib\unittest\suite.py", line 153, in _handleClassSetUp
    self._addClassOrModuleLevelException(result, e, errorName)
  File "C:\Python27\lib\unittest\suite.py", line 198, in _addClassOrModuleLevelException
    result.addError(error, sys.exc_info())
  File "C:\Python27\lib\HTMLTestRunner.py", line 598, in addError
    if self.verbosity > 1:
  File "C:\Python27\lib\HTMLTestRunner.py", line 570, in complete_output
    return self.outputBuffer.getvalue()
AttributeError: '_TestResult' object has no attribute 'outputBuffer'

**Comment by TomoyaJ** [comment]
I'm close this issue due I find out the root cause is related by 'self._addClassOrModuleLevelException(result, e, errorName)'
there was an exception didn't responsed.
